# Datadrevet Ledelse og kvalitetsforbedring

Formålet med Datadrevet Ledelse er, at tilvejebringe en fælles platform for kvalitetsudvikling og forbedring af kliniske og organisatoriske processer på alle niveauer i Bispebjerg og Frederiksberg Hospital. Dette sker ved at omsætte, fortolke og præsentere data på en måde, der skaber transparens og understøtter strategisk beslutningstagen baseret på valide data. 

Datadrevet Ledelse er et bærende element i hospitalets arbejde med den regionale strategi om fokus og forenkling. 

* Fokus skabes gennem en nøje prioritering af hvilke meningsfyldte indikatorer direktion, afdelingsledelser og afsnitsledelser skal fokusere på. 

* Forenkling skabes ved, at de valgte indikatorer skal kunne monitoreres ved hjælp af synlige og tilgængelige data, ligesom indikatorvalgene indebærer en lang række bevidste fravalg af andre indikatorer.

Datadrevet Ledelse er samtidig det gennemgående metodiske styringsredskab i hospitalets indsatser for at leve op til de nationale kvalitetsmål, samt den regionale driftsmålstyring.

## Nationale kvalitetsmål og regional driftsmålstyring
Tavlerne er det strukturelle omdrejningspunkt for Bispebjerg og Frederiksberg Hospitals arbejde med regionenens fem driftsmålsområder: Tilfredshed, Levering, Kvalitet, Produktivitet samt Medarbejdere og ledere. På tavlerne er der afsat en række til hvert område, som illustreret i figur 1 nedenfor.

## Data og tavlemøder
Datadrevet Ledelse indebærer, at strategiske beslutninger i organisationen skal understøttes af data, og at tavlemøder skal være en platform for kvalitetsforbedringsarbejde. 

Tavlerne har en opbygning som erfaringsmæssigt er velegnet til at give overblik over mål og data (tavlens venstre del), og til at give plads til arbejdet kvalitetsforbedringer (tavlens højre del). 

REGIONALE OG NATIONALE DRIFTSMÅL IND HER?
 
Seriediagrammer anvendes på tavlens venstre del i alle tilfælde hvor det er fagligt meningsgivende, til at vise og understøtte analyser data.

Til brug for det forbedringsarbejde som skal foregå på tavlens højre del, præsenteres i de efterfølgende kapitler en række enkle værktøjer, som kan anvendes til at identificere årsager til kvalitetsproblemer, samt strukturere arbejdet med at finde og implementere kvalitetsforbedringer.