# Fokusér på kvalitetsproblemer
Bispebjerg og Frederiksberg Hospitals ydelser kan – meget generaliseret – beskrives som resultatet af tusindvis af processer, der hver består af et antal forbundne trin som har et formål og en funktion. Processerne påvirker – og er afhængige af – det system de befinder sig i.

For at forbedre og forenkle en proces, er det nødvendigt at sætte fokus på at raffinere og optimere de enkelte trin i processen, gøre dem mere effektive, og fjerne trin som er overflødige. 

I dette arbejde kan man få god hjælp af forskellige værktøjer som beskrives i det følgende. Der er værktøjer, som viser data fra en proces, og der er værktøjer som hjælper med at finde og analysere årsager til kvalitetsproblemer. 
Når de mulige årsager til et kvalitetsproblem er identificeret, starter arbejdet med at finde og implementere handlinger der kan imødegå årsagerne (se 2.3 Sammensæt et kvalitetsforbedringsteam og 3 Værktøjer til kvalitetsforbedring).

## Vis data fra en proces
Det naturlige udgangspunkt for kvalitetsforbedringsarbejde er, at en given proces ikke lever op til sin målsætning.

Seriediagrammer er særligt egnede til at følge data fra en proces over tid, med henblik på at synliggøre problemer, og de bør anvendes overalt hvor det er meningsgivende. 
VÆRKTØJ	SE KAPITEL	HVORNÅR BRUGES DET?
Seriediagram	3.1
Til at vise data fra en proces over tid, for at se om en målsætning nås, samt om processen i øvrigt er stabil. Bruges også til at undersøge om en ændring der er gennemført fx ifm. kvalitetsarbejde, fører til en forbedring.
Søjlediagrammer mv?		
TABEL 1

## Find og analysér årsager
Hvis et seriediagram viser at der er problemer med kvaliteten i en proces, kan en række forskellige værktøjer hjælpe med at pege på mulige årsager. Værktøjerne hjælper med at svare på:

1. Hvor i processens forløb opstår problemet? (Forløbsdiagram)
2. Hvad tror vi årsagerne til problemet er? (Årsags-/virkningsdiagram, 5 x Hvorfor)
3. Hvad er de egentlige årsager til problemet? (Optællingsskemaer og Paretodiagram)

Nedenstående tabel beskriver kort de forskelige værktøjer og hvornår de kan anvendes. Værktøjerne er beskrevet i flere detaljer i kapitel 3 Værktøjer til kvalitetsforbedring
VÆRKTØJ	SE KAPITEL	HVORNÅR BRUGES DET?

<<<<<<< HEAD:02.Rmd
<<<<<<< HEAD:02.Rmd
```{r, echo=FALSE}
knitr::kable(
  head(mtcars[, 1:8], 10), booktabs = TRUE,
  caption = 'A table of the first 10 rows of the mtcars data.'
)
```


| Metode                             |            | Bruges til at ...                                                                         |
|:-----------------------------------|:-----------|:------------------------------------------------------------------------------------------|
| Forløbsdiagram                     | 3.2        | danne overblik og forstå de forskellige trin i en proces, samt identificere hvor kvalitetsproblemer opstår |
| Årsags-/virkningsdiagram           | 3.3        | brainstorme om hovedårsagerne til et kvalitetsproblem, samt hvilke underårsager der bidrager til hver årsag |
| 5 x Hvorfor                        | 3.4        | grave dybere ned i forståelsen af (kerne-)årsagerne til et problem. |
| Optællingsskemaer og Paretodiagram | 3.5        | indsamle data om kvalitetsproblemet, til at identificere de vigtigste kilder til problemet og til grafisk at fremstille årsagerne til kvalitetsproblemet |

=======
=======
>>>>>>> 479776abeba19c427692e734ec505a4c1f49229e:01-kapitel-1.Rmd
|   |   |   |
|---|---|---|
|Forløbsdiagram|3.2|Til at danne overblik og forstå de forskellige trin i en proces, samt identificere hvor kvalitetsproblemer opstår|
|Årsags-/virkningsdiagram |3.3|Ved brainstorm om hovedårsagerne til et kvalitetsproblem, samt hvilke under¬årsager der bidrager til hver årsag|
|   |   |
|   |   |
	

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

5 x Hvorfor	3.4
Til at grave dybere ned i forståelsen af (kerne-)årsagerne til et problem.
Optællingsskemaer og Paretodiagram	3.5
Til at indsamle data om kvalitetsproblemet, til at identificere de vigtigste kilder til problemet og til grafisk at fremstille årsagerne til kvalitetsproblemet
<<<<<<< HEAD:02.Rmd
>>>>>>> 479776abeba19c427692e734ec505a4c1f49229e:01-kapitel-1.Rmd
=======
>>>>>>> 479776abeba19c427692e734ec505a4c1f49229e:01-kapitel-1.Rmd
TABEL 2

Dataenheden på Bispebjerg og Frederiksberg Hospital har udarbejdet en MS Excel-fil (Hjælpeværktøjer til kvalitetsforbedring – den findes på Insite under ’Data’), som indeholder skabeloner til brug eller inspiration for forbedringsarbejdet. 

## Sammensæt et kvalitetsforbedringsteam
Når det praktiske arbejde med forbedring af en proces skal igangsættes, håndteres det bedst af et mindre team (fx op til højst 5-8 personer). Opbakning fra den samlede personalegruppe og ledelse er naturligvis vigtig at have med hele vejen. 

Identificér en teamleder som har tilstrækkelig pondus blandt kollegerne. Vær gerne åben overfor at inkludere folk som har legitime forbehold, og som er indstillet på at give konstruktiv kritik. Overvej at invitere en kollega fra et andet afsnit eller afdeling, som kender til tilsvarende problematikker, eller som er (med-)’ejer’ af en relateret proces.

Overvej følgende, når jeres et team skal sammensættes:

* Har vi en repræsentant fra de fagområder/discipliner, som har med processen at gøre?
* Har vi overvejet folk, som ikke er læger eller sygeplejersker?
* Har vi udpeget en teamleder?
* Er der nogen som skal have særligt ansvar for at sikre det faglige niveau?
* Har vi overvejet at inkludere en konstruktiv skeptiker i teamet?
* Er der nogen der har erfaring med kvalitetsforbedring, som kan facilitere forbedringsarbejdet?
* Har vi overvejet at inkludere en ekstern interessent? 
* Har vi overvejet at inkludere en repræsentant for patienter eller pårørende?

