# Værktøjer til kvalitetsforbedring
## Seriediagram
Seriediagrammer er et bærende element i arbejdet med Datadrevet Ledelse på Bispebjerg og Frederiksberg Hospital. Det skyldes blandt andet, at et af seriediagrammets væsentlige styrker er, at det sætter fokus på om data har et niveau eller en retning. 

Netop niveau og retning – dvs. informationer om processens målopfyldelse og udvikling over tid – er helt centrale for at fastslå om processen leverer kvalitet på tilfredsstillende niveau, og om kvaliteten eventuelt er blevet forbedret eller forringet. 

Dataenheden på Bispebjerg og Frederiksberg Hospital opdaterer og udsender ugentligt seriediagrammer for en række centrale kvalitetsindikatorers vedkommende.
For indikatorer som har lokal karakter og hvor man interesserer sig for at overvåge kvaliteten, vil der være behov for at den enkelte afdeling eller afsnit selv laver seriediagrammer. Til dette formål findes en MS Excel-skabelon som kan anvendes til at fremstille seriediagrammer. Skabelonen kan hentes på Insite under ’Data’. 
 
FIGUR 2
Læsningen af seriediagrammer understøttes af en række supplerende informationer, der ses i et samlet layout i figur 2. 

###Seriediagrammets elementer
Det layout for seriediagrammer som anvendes på Bispebjerg og Frederiksberg Hospital kan opdeles i 5 hovedelementer, som gennemgås i det efterfølgende. 

1. Oplysninger om den aktuelle indikator, og navnet på afdeling eller afsnit.
2. Hovedelementet i et seriediagram er en graf, som består af målepunkter i kronologisk rækkefølge. Målepunkterne angives på værdiaksen og er forbundne. De skal illustrere hvordan en proces opfører sig over tid.

    Medianen i data – det vil sige den midterste værdi, hvis man sorterer datasættet – angives langs tidsaksen som en rød lige linje, for at synliggøre hvor de enkelte målepunkter ligger i forhold til denne. Langs tidsaksen indtegnes også målsætningen med grå stiplet linje. Der kan være flere medianer indtegnet, hvis grafen over tid har vist en signifikant forbedring eller forværring i kvalitetsniveau.

    Diagrammet viser desuden en kort beskrivelse øverst af data, hvor mange observationer der gennemsnitligt indgår i et enkelt datapunkt, og hvor mange observationer der indgår i det seneste datapunkt.

3. Målsætningen for indikatoren angives sammen med medianværdien, som et udtryk for i hvor høj grad målsætningen nås.
4. En kort datadefinition og eventuelle relevante kommentarer til data, samt information om processen indeholder tilfældig variation, eller – hvis den ikke gør – på hvilken måde processen er ikke-tilfældig.
5. En tendenskurve samt en grafisk indikation af om processen er stabil eller ikke stabil (hhv. tilfældig og ikketilfældig variation).

Tendenskurven skal tages som en visualisering af om det ”går den rigtige vej”. Den dannes på baggrund af de enkelte datapunkters kumulerede afstand til den aktuelle median, og udviser derfor en lidt højere følsomhed overfor ændringer i en proces en det egentlige seriediagram. Den kan derfor tjene som en tidlig advarsel om at data er ved at ændre retning.

### Fortolkning af seriediagrammet
Som nævnt ovenfor, er særligt niveau og retning i data væsentlige for fortolkningen af data. 

Seriediagrammets median angiver det aktuelle niveau for den pågældende proces, og den skal vurderes i forhold til det mål som er sat for processen.

Hvis niveauet i kvaliteten er tilfredsstillende kan data derefter monitoreres løbende for at sikre at processen vedbliver at være stabil på det ønskede kvalitetsniveau.

Man tilstræber normalt at datapunkter varierer tilfældigt omkring medianen i et datasæt. Tilfældig variation er et udtryk for at en given proces er stabil, mens ikke-tilfældig variation er et tegn på at ”noget” styrer data, og at processen derfor ikke er stabil.

Hvis en proces viser ikke-tilfældig variation, så betyder det at datapunkterne er begyndt at få en anden retning end den tilfældige bevægelse omkring medianen – med andre ord vil  det ikke længere være tilfældigt om næste datapunkt falder over eller under medianen. Hvis retningen er positiv, fx øget patienttilfredshed eller et fald i ventetider, så er det et udtryk for at data viser at en kvalitetsforbedring er signifikant.

Hvis retningen er negativ så er det anledning til at analysere hvad der er begyndt at styre data, og derefter iværksætte forbedringsarbejde for at få retningen tilbage på kurs og niveau.

Hvis et team arbejder med at forbedre en proces og variationen af data bliver ved at være tilfældig, så har ændringerne endnu ikke ført til dokumentérbare forbedringer. Det er nødvendigt at vende tilbage til Forbedringsmodellen, analyseværktøjer og PDSA-cyklusser. 

## Forløbsdiagram
Et forløbsdiagram, også kendt som Flowchart eller Procesmodel, er en kortlægning af de forskellige trin i en proces – for eksempel de trin som et ambulatorium gennemgår for at levere en bestemt behandling. Forløbsdiagrammet kan give overblik over et helt forløb, og hjælper teams med at fokusere på procestrin som har problemer. 

Et traditionelt forløbsdiagram er ofte meget detaljeret, og derfor kan man overveje om et overordnet forløbsdiagram, evt. med supplerende kommentarer i punktform, er tilstrækkeligt til at give det fornødne indblik i processens trin.
 
FIGUR 3 – Traditionelt forløbsdiagram (fra ”Implementering af Nationale Kliniske Retningslinjer”, Sundhedsstyrelsen.dk)

FIGUR 4 – Overordnet forløbsdiagram (fra ”Implementering af Nationale Kliniske Retningslinjer”, Sundhedsstyrelsen.dk)

**Trin-for-trin vejledning**

1. Saml gruppen som skal arbejde med at definere et forløbsdiagram. Væsentlige interessenter bør være repræsenteret.
2. Fastlæg hvad start og slutpunktet i forløbene er.
3. Fokusér på at kortlægge de vigtigste dele af processerne – brug ikke for meget tid på undtagelserne.
4. Forløbsdiagrammet skal vise de faktiske processer, ikke de ideelle.
5. Benyt fx. et whiteboard eller post-it-sedler til at udarbejde diagrammet.

## Årsags-/virkningsdiagram
Årsags-/virkningsdiagrammet (eller fiskebensdiagrammet) er et enkelt værktøj, som kan bruges til at strukturere en brainstorm og lave en grafisk visning af mulige årsager til et problem. Et årsags-/virkningsdiagram (se figur 5) er et vigtigt skridt i kvalitetsforbedringsarbejde, og det kan hjælpe med at sikre at et forbedringsteam har det nødvendige overblik over mulige årsager til problemet, før teamet går i gang med at finde løsninger.
 
FIGUR 5 - Udsnit af et eksempel på et udfyldt årsags-/virkningsdiagram

**Trin-for-trin vejledning**

Udskriv skabelonen til årsags-/virkningsdiagrammet fra Excel-filen Hjælpeværktøjer til kvalitetsforbedring, som findes på Insite under ’Data’, og udfyld i hånden ved at

1. Formulere problemet så kort og entydigt som muligt, og skriv ind i boksen til højre (under virkning)
2. Justér evt. hovedkategorierne på de fem ben så de er dækkende for den konkrete kontekst, og tilføj eller fjern ben efter behov.
3. Når de vigtigste hovedgrupper er placeret, er det en god idé at give god plads til at teamet kan arbejde kreativt med at finde årsager. Bed teamet overveje hvert ben i diagrammet, og ikke fokusere for meget opmærksomhed på kun en enkelt eller to årsagskategorier. Det er bedst ikke at diskutere idéerne på dette niveau af brainstormingsprocessen.
4. Skriv dernæst de årsager, som teamet mener, bidrager til problemet, ind under de rette ben i diagrammet. 
5. Teamet kan beslutte at indtegne yderligere underårsager til de identificerede årsager direkte i diagrammet, eller en blank skabelon kan anvendes til at visualisere næste niveau under en årsag. Gentag efter behov, indtil årsags/virkningskomplekset er afdækket i tilstrækkelig grad til at teamet kan arbejde videre.

Excel-skabelonen indeholder mulighed for, at man indtaster problem og mulige årsager direkte i et redigeringsfaneblad, hvorefter det færdig årsags-/virkningsdiagram kan printes ud.

Når årsags-/virkningsdiagrammet er færdigt, kan teamet begynde at bedømme resultatet, for at forstå og analysere årsagerne til problemet. 

## 5 X Hvorfor
”5 x Hvorfor” er et simpelt værktøj til brainstorming, som hjælper forbedringsteams med at finde grundlæggende årsager bag et problem. Når teamet har identificeret årsager til et problem ved hjælp af enten Årsags-/virkningsdiagrammer, så stil så mange ”hvorfor?”-spørgsmål som muligt, for at bore ned igennem de enkelte årsager. Stop når svarene ikke længere giver mening, set i relation til spørgsmålet.

Problem:
Jeg er for dårlig til at danse vals 
	Hvorfor?
	Jeg har ikke styr på trinene 
		Hvorfor?
		Jeg mangler øvelse
			Hvorfor?
			Jeg har ikke fået øvet dem med min dansepartner
				Hvorfor?
				Hun har været syg de sidste 3 gange

FIGUR 6 – Eksempel på 5 x Hvorfor

Denne arbejdsform giver teams mulighed for at se videre end de mest åbenlyse svar, og at reflektere over mindre indlysende forklaringer.

**Trin-for-trin vejledning**
1. Spørg ”hvorfor” har vi problemet 
2. Spørg ”hvorfor” til årsagen. Bliv ved at spørge ”hvorfor” til hver foreslået årsag (på samme måde som en spørgelysten 3-årig kunne gøre).
3. Spørg så mange gange der er behov for, for at få problemet brudt ned i størrelser som der kan arbejdes med (5 gange er typisk, men det kan være flere eller færre gange)

”5 x Hvorfor” bruges som regel til at udforske et problem i dybden, ved at fokusere på at finde årsager, som måtte ligge bag dem som teamet mener er primære. Metoden kan hjælpe med at sikre, at man undgår bias eller at fokusere for snævert.

## Simpel optælling og paretodiagram
Et optællingsskema er et simpelt værktøj til at samle data, som kan hjælpe et team med at identificere den eller de vigtigste årsager bag et kvalitetsproblem. Helt konkret bruges optællingsskemaet til at dokumentere frekvensen af årsager til et problem, og det er særligt nyttigt når teamet allerede har identificeret et antal mulige årsager eller fejlkilder.
 
FIGUR 7

**Trin-for-trin vejledning**

1. Lav en liste over de mest almindelige årsager til det pågældende problem. Hvis du allerede har lavet et årsags-/virkningsdiagram, så brug årsagerne derfra. Skriv så mange ned som nødvendigt – en typisk liste indeholder 6 til 10 årsager. Tilføj også en ”Andet”-årsag.
2. Skriv årsagerne ind i et optællingsskema som oven for - Excel-skabelon Hjælpeværktøjer til kvalitetsforbedring, der kan findes på Insite under ’Data’ indeholder et forslag til et optællingsskema som enten kan printes og bruges, eller som kan udfyldes direkte på PC’en. 
3. Beslut hvordan data skal indsamles – Skal der samles data ind fremadrettet, eller findes der historiske data. Skal der foretages audits, eller bruges anden dokumentation?
4. Fastsæt en tidsramme for dataindsamlingen. Tidsrammen bør være lang nok til at lave fx 50 fund. Hvis data samles ind fremadrettet, så forsøg at holde indsamlingsperioden kort (fx 1 uge).
5. Identificér hvem skal indsamle data, og bed dem sætte en streg ud for hver årsag de observerer. Vær tydelig omkring hvordan årsagerne er defineret.
6. Opgør hvilke årsager der har haft flest fund, og fokusér på disse i det kommende forbedringsarbejde. Tegn evt. data ind i et Paretodiagram ved hjælp af det medfølgende værktøj, som beskrevet nedenfor.

Et Paretodiagram er et værktøj, som hjælper et team med at vise årsager eller områder som bidrager mest til det undersøgte kvalitetsproblem. Paretodiagrammet bygger på en teori om, at et lille antal årsager er de største ”syndere” i en proces. Når størstedelen af en problematik kan henføres til et lille del af de mulige årsager, kaldes det Paretoeffekt. Et klassisk eksempel på en Paretoeffekt er når 20% af det man gør, resulterer i 80% af problemerne.

Selve diagrammet viser antal observationer af hvert problem i søjler, og viser samtidigt det akkumulerede antal i procent, for at gøre det enkelt at identificere hvilke årsager der bidrager til hovedparten af problemet (her 80%).

**Trin-for-trin vejledning**

1. Lav en optælling som beskrevet ovenfor, fx ved hjælp af Optællings-skema-skabelonen
2. Indtast årsager og antal observationer i redigeringsfanebladet til Paretodiagrammer i Excel-skabelonen Hjælpeværktøjer til kvalitetsforbedring, som findes på Insite under ’Data’.
3. Udskriv det færdige Paretodiagram og fokusér forbedringsarbejdet på de væsentligste årsager til problemet.
