---
title: "Metoder til at understøtte kvalitetsforbedring"
author: "Enhed for Kvalitet, Bispebjerg og Frederiksberg Hospital"
output:
  bookdown::gitbook: default
  bookdown::pdf_book: default
site: bookdown::bookdown_site
documentclass: book
---

# Datadrevet ledelse og kvalitetsforbedring {-}

Alle ledelsesniveauer på Bispebjerg og Frederiksberg Hospital har siden 2015 arbejdet med datadrevet ledelse. Det overordnede formål er, at tilvejebringe en fælles platform for kvalitetsudvikling og forbedring af kliniske og organisatoriske processer i hele organisationen. 

Formålet med Datadrevet Ledelse er at omsætte, fortolke og præsentere data på en måde, der skaber transparens og understøtter strategisk beslutningstagen baseret på valide data. Datadrevet Ledelse er samtidig et bærende element i Bispebjerg og Frederiksberg Hospitals arbejde med den regionale strategi om fokus og forenkling. 
Fokus skabes gennem en nøje prioritering af hvilke meningsfyldte indikatorer direktion, afdelingsledelser og afsnitsledelser skal fokusere på. 

Forenkling skabes ved, at de valgte indikatorer skal kunne monitoreres ved hjælp af synlige og tilgængelige data, ligesom indikatorvalgene indebærer en lang række bevidste fravalg af andre indikatorer.

## Data og tavlemøder
Datadrevet Ledelse indebærer, at den strategiske beslutningstagen i organisationen skal understøttes af data, og at tavlemøder skal være en platform for kvalitetsforbedringsarbejde. 

Tavlerne har en opbygning som erfaringsmæssigt er velegnet til dels at give overblik over mål og data (tavlens venstre del), og til dels at give plads til arbejdet med analyser af årsager til kvalitetsproblemer, og de tilknyttede handlinger som skal resultere i ændringer af de pågældende processer (tavlens højre del). 

Tavlerne bliver det strukturelle omdrejningspunkt for Bispebjerg og Frederiksberg Hospitals arbejde med regionenens fem driftsmålsområder: Tilfredshed, Levering, Kvalitet, Produktivitet  samt Medarbejdere og ledere. På tavlen er der afsat en række til hvert område, som illustreret i figur 1 nedenfor.
REGIONALE DRIFTSMÅL IND HER?
 

Det er besluttet, at seriediagrammer anvendes på tavlens venstre del i alle tilfælde hvor det er fagligt meningsgivende, til at vise og analysere data.

Til brug for det forbedringsarbejde som skal foregå på tavlens højre del, præsenteres i de efterfølgende kapitler en række enkle værktøjer, som kan anvendes til at identificere årsager til kvalitetsproblemer, samt strukturere arbejdet med at finde og implementere kvalitetsforbedringer.

Datadrevet Ledelse er et udviklingsprojekt og det er både omfattende og nyt for mange medarbejdere. Der er derfor også stor åbenhed omkring det faktum, at der kan være behov for at justere undervejs. 
